export const siteConfig = {
  name: "DRM Corbeil-Essonnes",
  fullName: "Depannage Rideau Metallique Corbeil-Essonnes",
  domain: "depannage-rideau-metallique-corbeil-essonnes.com",
  url: "https://depannage-rideau-metallique-corbeil-essonnes.com",
  phone: "01 84 18 04 99",
  phoneLink: "tel:+33184180499",
  telephoneHref: "tel:+33184180499",
  email: "contact@depannage-rideau-metallique-corbeil-essonnes.com",
  city: "Corbeil-Essonnes",
  cityShort: "Corbeil-Essonnes",
  postalCode: "91100",
  department: "Essonne",
  departmentCode: "91",
  region: "Ile-de-France",
  address: "106 Rue de Gournay, 91100 Corbeil-Essonnes",
  addressStreet: "106 Rue de Gournay",
  geo: {
    latitude: 48.6139,
    longitude: 2.4828,
  },
  openingHours: "24h/24, 7j/7",
  experience: "25+",
  delai: "30",
  rating: "4.9",
  ratingCount: "127",
  interventions: "5000+",
  siret: "",
};

export const services = [
  {
    id: "depannage",
    name: "Depannage",
    slug: "depannage-rideau-metallique",
    description: "Intervention urgence 24h/24 sur rideau metallique en panne a Corbeil-Essonnes",
    shortDescription: "Rideau bloque ? Intervention en moins de 30 minutes a Corbeil-Essonnes.",
  },
  {
    id: "installation",
    name: "Installation",
    slug: "installation-rideau-metallique",
    description: "Pose complete de rideaux metalliques neufs pour commerces et industriels a Corbeil-Essonnes",
    shortDescription: "Pose sur-mesure pour commerces, bureaux et entrepots.",
  },
  {
    id: "reparation",
    name: "Reparation",
    slug: "reparation-rideau-metallique",
    description: "Remise en etat de rideaux metalliques endommages a Corbeil-Essonnes",
    shortDescription: "Lames, moteur, axe, serrure : reparation garantie.",
  },
  {
    id: "motorisation",
    name: "Motorisation",
    slug: "motorisation-rideau-metallique",
    description: "Automatisation de rideaux metalliques manuels existants a Corbeil-Essonnes",
    shortDescription: "Passez a l'electrique avec Somfy, Simu ou Nice.",
  },
  {
    id: "deblocage",
    name: "Deblocage",
    slug: "deblocage-rideau-metallique",
    description: "Liberation urgente de rideaux metalliques coinces a Corbeil-Essonnes",
    shortDescription: "Rideau coince ? Liberation rapide sans degradation.",
  },
  {
    id: "entretien",
    name: "Entretien",
    slug: "entretien-rideau-metallique",
    description: "Maintenance preventive et contrats annuels a Corbeil-Essonnes",
    shortDescription: "Evitez les pannes avec un entretien regulier.",
  },
  {
    id: "fabrication",
    name: "Fabrication",
    slug: "fabrication-rideau-metallique",
    description: "Fabrication sur-mesure de rideaux metalliques a Corbeil-Essonnes",
    shortDescription: "Acier, aluminium, inox : fabrication aux dimensions exactes.",
  },
];

export const zones = [
  { name: "Evry-Courcouronnes", slug: "evry-courcouronnes", postalCode: "91000", distance: "3 km" },
  { name: "Villabe", slug: "villabe", postalCode: "91100", distance: "2 km" },
  { name: "Le Coudray-Montceaux", slug: "le-coudray-montceaux", postalCode: "91830", distance: "3 km" },
  { name: "Saint-Germain-les-Corbeil", slug: "saint-germain-les-corbeil", postalCode: "91250", distance: "4 km" },
  { name: "Lisses", slug: "lisses", postalCode: "91090", distance: "5 km" },
  { name: "Etiolles", slug: "etiolles", postalCode: "91450", distance: "5 km" },
  { name: "Soisy-sur-Seine", slug: "soisy-sur-seine", postalCode: "91450", distance: "4 km" },
  { name: "Ris-Orangis", slug: "ris-orangis", postalCode: "91130", distance: "4 km" },
  { name: "Draveil", slug: "draveil", postalCode: "91210", distance: "7 km" },
  { name: "Mennecy", slug: "mennecy", postalCode: "91540", distance: "10 km" },
  { name: "Grigny", slug: "grigny", postalCode: "91350", distance: "8 km" },
  { name: "Viry-Chatillon", slug: "viry-chatillon", postalCode: "91170", distance: "10 km" },
  { name: "Savigny-sur-Orge", slug: "savigny-sur-orge", postalCode: "91600", distance: "12 km" },
  { name: "Athis-Mons", slug: "athis-mons", postalCode: "91200", distance: "13 km" },
  { name: "Juvisy-sur-Orge", slug: "juvisy-sur-orge", postalCode: "91260", distance: "14 km" },
  { name: "Morsang-sur-Orge", slug: "morsang-sur-orge", postalCode: "91390", distance: "12 km" },
  { name: "Fleury-Merogis", slug: "fleury-merogis", postalCode: "91700", distance: "10 km" },
  { name: "Sainte-Genevieve-des-Bois", slug: "sainte-genevieve-des-bois", postalCode: "91700", distance: "12 km" },
  { name: "Brunoy", slug: "brunoy", postalCode: "91800", distance: "10 km" },
  { name: "Yerres", slug: "yerres", postalCode: "91330", distance: "10 km" },
  { name: "Montgeron", slug: "montgeron", postalCode: "91230", distance: "10 km" },
  { name: "Epinay-sous-Senart", slug: "epinay-sous-senart", postalCode: "91860", distance: "10 km" },
];

export const colors = {
  primary: "#1A1F2E",
  primaryDark: "#0F1419",
  accent: "#E85D04",
  accentLight: "#FFB627",
  accentHover: "#C44100",
  lightBg: "#F5F3EE",
  warmBg: "#FAEBDD",
  darkBg: "#0F1419",
  white: "#FFFFFF",
  textDark: "#1A1F2E",
  textMuted: "#6B7280",
  textLight: "#9CA3AF",
  border: "#E5E7EB",
  starColor: "#F59E0B",
};

export const marques = [
  "Somfy", "Simu", "ACM", "Came", "Nice", "FAAC", "BFT", "Sommer",
];
