export interface ZoneLocal {
  slug: string;
  quartiers: string[];
  rues: string[];
  landmarks: string[];
  commerces: string[];
  profile: "urbain" | "residentiel" | "mixte";
  description: string;
}

export const zonesLocal: Record<string, ZoneLocal> = {
  "evry-courcouronnes": {
    slug: "evry-courcouronnes",
    quartiers: ["Centre-ville d'Evry", "Pyramides", "Bois-Sauvage", "Epinettes", "Parc aux Lievres", "Mousseau", "Coquibus"],
    rues: ["Boulevard de France", "Place des Terrasses de l'Agora", "Cours Blaise-Pascal", "Rue du Bois-Sauvage", "Avenue de l'Universite", "Boulevard des Champs-Elysees"],
    landmarks: ["Cathedrale de la Resurrection", "Genopole", "Theatre de l'Agora", "Universite d'Evry", "Prefecture", "Stade Robert Bobin"],
    commerces: ["Agora d'Evry", "Carrefour Evry", "commerces du quartier des Pyramides", "boutiques du centre commercial Evry 2"],
    profile: "urbain",
    description: "Prefecture de l'Essonne, ville nouvelle a forte densite commerciale avec le pole Evry 2 et le quartier d'affaires Genopole",
  },
  "villabe": {
    slug: "villabe",
    quartiers: ["Centre-ville", "La Quintine", "Le Bois des Plantes", "Chateau Guillebon"],
    rues: ["Rue du Chateau", "Rue Gambetta", "Avenue de la Gare", "Rue du 14 Juillet", "Route de Lisses"],
    landmarks: ["Parc Mercier", "Eglise Saint-Martin", "Chateau Guillebon", "ZAC du Levant"],
    commerces: ["Zone d'activites de la Gare", "commerces centre-ville", "Villabe Parc des Levants"],
    profile: "mixte",
    description: "Commune residentielle et commerciale limitrophe de Corbeil, avec la zone d'activites Levants",
  },
  "le-coudray-montceaux": {
    slug: "le-coudray-montceaux",
    quartiers: ["Centre-bourg", "Les Montceaux", "Montceaux Est", "La Vallee"],
    rues: ["Route de Milly", "Avenue du General de Gaulle", "Rue de l'Eglise", "Rue des Montceaux", "Route de Corbeil"],
    landmarks: ["Eglise Saint-Germain", "Ferme de Montceaux", "ZA des Tournelles", "Bord de Seine"],
    commerces: ["Centre commercial des Tournelles", "commerces de proximite du bourg"],
    profile: "mixte",
    description: "Commune au sud de Corbeil, bordee par la Seine, avec tissu commercial moyen et zone industrielle Tournelles",
  },
  "saint-germain-les-corbeil": {
    slug: "saint-germain-les-corbeil",
    quartiers: ["Centre-ville", "Le Parc", "Quartier du Golf", "Les Tourelles"],
    rues: ["Avenue du General de Gaulle", "Rue de l'Eglise", "Boulevard du Parc", "Rue du Golf", "Avenue de l'Europe"],
    landmarks: ["Golf de Corbeil-Saint-Germain", "Chateau Saint-Germain", "Eglise Saint-Germain", "ZI du Parc"],
    commerces: ["Commerces du centre", "ZA de l'Europe"],
    profile: "residentiel",
    description: "Commune residentielle huppee au sud de Corbeil, proche du Golf, forte presence de residences pavillonnaires",
  },
  "lisses": {
    slug: "lisses",
    quartiers: ["Centre-ville", "Hameau de Rougeau", "Quartier du Long-Rayage", "Les Folies"],
    rues: ["Avenue de l'Orme a Martin", "Rue du Long-Rayage", "Avenue du 8 Mai", "Rue de la Liberte", "Boulevard de l'Europe"],
    landmarks: ["Parc Leon-Cassagne", "Eglise Saint-Pierre", "ZI Leonard de Vinci", "Le Long-Rayage"],
    commerces: ["Zone industrielle Leonard de Vinci", "Commerces centre Lisses", "ZAC du Long-Rayage"],
    profile: "mixte",
    description: "Commune industrielle et commerciale, avec la grande ZI Leonard de Vinci qui concentre entrepots et commerces B2B",
  },
  "etiolles": {
    slug: "etiolles",
    quartiers: ["Centre-ville", "Le Bois de Saint-Germain", "Quartier de la Foret"],
    rues: ["Avenue du Chateau", "Rue de la Mairie", "Rue des Bois", "Route de Ponthierry", "Avenue du Golf"],
    landmarks: ["Chateau d'Etiolles", "Golf d'Etiolles", "Eglise Saint-Maurice", "Bois de Saint-Germain"],
    commerces: ["Commerces du centre", "Boulangeries, pharmacie, tabac"],
    profile: "residentiel",
    description: "Commune residentielle huppee en bordure de foret, tissu commercial faible, nombreuses maisons individuelles",
  },
  "soisy-sur-seine": {
    slug: "soisy-sur-seine",
    quartiers: ["Centre-ville", "Petit-Soisy", "Le Parc aux Cerfs", "Quartier de la Seine"],
    rues: ["Rue de la Seine", "Avenue du General Leclerc", "Rue du Chateau", "Boulevard du Parc", "Rue de Corbeil"],
    landmarks: ["Bords de Seine", "Eglise Saint-Germain", "Parc du Chateau", "Halle de Soisy"],
    commerces: ["Marche de Soisy", "Commerces du centre", "Bord de Seine touristique"],
    profile: "mixte",
    description: "Commune bordee par la Seine, ambiance village avec commerces de proximite et port de plaisance",
  },
  "ris-orangis": {
    slug: "ris-orangis",
    quartiers: ["Centre-ville", "Les Docks", "Le Plateau", "Gare RER", "La Plaine"],
    rues: ["Boulevard de la Republique", "Rue du General Leclerc", "Avenue de la Gare", "Rue Pierre Brossolette", "Boulevard Marc-Sangnier"],
    landmarks: ["Mairie de Ris-Orangis", "Gare RER D", "Hippodrome", "Stade Robert-Bobin", "Parc des Docks"],
    commerces: ["Commerces de la gare", "Centre commercial des Docks", "ZA Plateau", "Marche hebdomadaire"],
    profile: "urbain",
    description: "Grande commune urbaine de l'Essonne avec gare RER D, hippodrome, zones commerciales des Docks et du Plateau",
  },
  "draveil": {
    slug: "draveil",
    quartiers: ["Centre-ville", "Les Mazieres", "La Villa", "Champrosay", "Mainville"],
    rues: ["Avenue Henri Barbusse", "Rue du Docteur Francois", "Boulevard du Chateau", "Avenue Libert", "Rue Pierre-Brossolette"],
    landmarks: ["Chateau de Draveil", "Foret de Senart", "Gare de Vigneux-Draveil", "Parc Champrosay"],
    commerces: ["Marche de Draveil", "Commerces centre-ville", "Avenue Libert"],
    profile: "residentiel",
    description: "Commune residentielle historique, proche de la foret de Senart, avec tissu commercial de centre-ville et artisanat local",
  },
  "mennecy": {
    slug: "mennecy",
    quartiers: ["Centre-ville", "Les Hauts de Mennecy", "Villeroy", "Le Plessis-Saint-Benoist"],
    rues: ["Rue de Paris", "Avenue Darblay", "Rue de Villeroy", "Boulevard des Vignes", "Rue du 8 Mai"],
    landmarks: ["Chateau de Villeroy", "Eglise Saint-Pierre", "Parc Darblay", "Gare RER D", "ZA Chamaille"],
    commerces: ["Marche de Mennecy", "Commerces de la Rue de Paris", "ZA Chamaille", "Centre commercial Darblay"],
    profile: "mixte",
    description: "Commune prospere au sud de Corbeil, avec gare RER D, commerces de centre-ville actifs et la ZA Chamaille",
  },
  "grigny": {
    slug: "grigny",
    quartiers: ["Centre-ville", "Grande Borne", "Grigny 2", "Quartier des Patios"],
    rues: ["Avenue des Tuileries", "Boulevard Rolland", "Rue de la Fontaine", "Rue Henri Douard", "Chemin de la Plaine Basse"],
    landmarks: ["Lac de Grigny", "Gare RER D Grigny-Centre", "Mairie de Grigny", "Parc de la Plaine Basse"],
    commerces: ["Marche de Grigny", "Centre commercial Grande Borne", "Commerces Rollinat"],
    profile: "urbain",
    description: "Commune urbaine de l'Essonne proche du plateau de Viry, tissu commercial dense et grands ensembles",
  },
  "viry-chatillon": {
    slug: "viry-chatillon",
    quartiers: ["Centre-ville", "Le Plateau", "Grigny-La Plaine", "Quartier des Aviateurs"],
    rues: ["Boulevard des Aviateurs", "Rue de l'Eglise", "Avenue de la Liberte", "Avenue Gambetta", "Rue de l'Hotel de Ville"],
    landmarks: ["Mairie de Viry-Chatillon", "Lac de Viry", "Parc des Grands Champs", "Gare RER D Viry-Chatillon"],
    commerces: ["Centre commercial des Aviateurs", "Marche de Viry", "Commerces de la Rue de l'Eglise"],
    profile: "urbain",
    description: "Commune urbaine dense au nord de Corbeil, avec RER D et nombreuses zones commerciales",
  },
  "savigny-sur-orge": {
    slug: "savigny-sur-orge",
    quartiers: ["Centre-ville", "Grand-Vaux", "Les Rossays", "Champagne"],
    rues: ["Avenue Charles de Gaulle", "Rue Charles-Rossignol", "Avenue de l'Armee Leclerc", "Rue Jean-Mermoz", "Rue Martha-Desrumaux"],
    landmarks: ["Chateau de Savigny", "Gare RER C Savigny-sur-Orge", "Mairie de Savigny", "Parc de Champagne"],
    commerces: ["Centre commercial de Savigny", "Commerces de la gare RER", "Marche de Savigny"],
    profile: "urbain",
    description: "Commune urbaine importante de l'Essonne avec gare RER C, tissu commercial actif et residentiel dense",
  },
  "athis-mons": {
    slug: "athis-mons",
    quartiers: ["Centre-ville", "Mons", "Les Gravilliers", "Clos Nollet", "Noyer-Renard"],
    rues: ["Avenue de Paris", "Avenue Jean-Jaures", "Rue Clos-Nollet", "Boulevard Pasteur", "Rue du Docteur-Vinot"],
    landmarks: ["Aeroport Paris-Orly", "Mairie d'Athis-Mons", "Gare RER C", "Parc des Gravilliers"],
    commerces: ["Centre commercial Ozone", "Commerces de l'Avenue de Paris", "Marche d'Athis-Mons"],
    profile: "urbain",
    description: "Commune importante de l'Essonne limitrophe de l'aeroport d'Orly, avec tissu commercial dense et nombreux bureaux",
  },
  "juvisy-sur-orge": {
    slug: "juvisy-sur-orge",
    quartiers: ["Centre-ville", "Gare de Juvisy", "Plateau de Juvisy", "Seine"],
    rues: ["Place Anatole-France", "Rue Argeliers-Pierre", "Avenue d'Estienne-d'Orves", "Grande Rue", "Rue Hoche"],
    landmarks: ["Gare RER C et D Juvisy", "Pont de Juvisy sur la Seine", "Observatoire de Juvisy", "Mairie"],
    commerces: ["Commerces de la gare Juvisy", "Marche de Juvisy", "Centre commercial de la Grande Rue"],
    profile: "urbain",
    description: "Noeud ferroviaire majeur d'Ile-de-France (RER C+D), tres grand flux de voyageurs, nombreux commerces de gare",
  },
  "morsang-sur-orge": {
    slug: "morsang-sur-orge",
    quartiers: ["Centre-ville", "Plateau", "La Grande-Rue", "Les Pres"],
    rues: ["Rue du General-de-Gaulle", "Avenue de la Republique", "Rue Marat", "Rue Jean-Raynal", "Boulevard de l'Orge"],
    landmarks: ["Mairie de Morsang-sur-Orge", "Eglise Saint-Martin", "Parc Beauregard", "Gare RER C"],
    commerces: ["Commerces centre", "ZA du Plateau", "Marche de Morsang"],
    profile: "mixte",
    description: "Commune de la vallee de l'Orge, tissu mixte residentiel et commercial, gare RER C",
  },
  "fleury-merogis": {
    slug: "fleury-merogis",
    quartiers: ["Centre-ville", "Les Tournelles", "Les Joncs-Marins"],
    rues: ["Rue des Joncs-Marins", "Avenue du Stade", "Rue du Plessis-Cornu", "Rue Mazarin", "Boulevard du Maronnier"],
    landmarks: ["Centre penitentiaire de Fleury-Merogis", "ZI du Plessis-Cornu", "Mairie de Fleury-Merogis"],
    commerces: ["ZI du Plessis-Cornu", "Commerces centre-ville", "Centre commercial local"],
    profile: "mixte",
    description: "Commune petite mais avec une grande zone industrielle Plessis-Cornu accueillant des dizaines d'entreprises",
  },
  "sainte-genevieve-des-bois": {
    slug: "sainte-genevieve-des-bois",
    quartiers: ["Centre-ville", "Les Cigales", "Le Bois des Roches", "Saintes-Maries"],
    rues: ["Boulevard Carnot", "Avenue Gabriel-Peri", "Rue Anatole-France", "Avenue de la Gare", "Rue Jean-Jaures"],
    landmarks: ["Gare RER C Sainte-Genevieve", "Mairie de Sainte-Genevieve", "Parc Pierre", "Eglise Sainte-Genevieve"],
    commerces: ["Commerces de la gare", "Centre commercial du Parc", "Marche de Sainte-Genevieve"],
    profile: "urbain",
    description: "Grande commune de l'Essonne avec gare RER C et vie commerciale dynamique, nombreux commerces de proximite",
  },
  "brunoy": {
    slug: "brunoy",
    quartiers: ["Centre-ville", "Les Hautes Mardelles", "Le Plateau"],
    rues: ["Rue de l'Eglise", "Avenue du General-Leclerc", "Boulevard du Peuple", "Rue de Paris", "Rue Monmousseau"],
    landmarks: ["Mairie de Brunoy", "Gare RER D Brunoy", "Eglise Saint-Medard", "Parc de Brunoy"],
    commerces: ["Commerces centre-ville", "Marche de Brunoy", "Rue de Paris commerçante"],
    profile: "urbain",
    description: "Commune residentielle a forte presence commerciale, gare RER D, centre-ville piétonnier",
  },
  "yerres": {
    slug: "yerres",
    quartiers: ["Centre-ville", "Le Chateau", "Quartier de la Gare", "Les Tilleuls"],
    rues: ["Grande Rue", "Avenue de l'Opera", "Rue Charles-de-Gaulle", "Rue du Moulin", "Boulevard Chanzy"],
    landmarks: ["Chateau de Yerres", "Gare RER D Yerres", "Mairie de Yerres", "Parc Gustave-Caillebotte"],
    commerces: ["Grande Rue piétonnière", "Commerces du centre", "Marche hebdomadaire de Yerres"],
    profile: "mixte",
    description: "Commune residentielle proche Paris, centre commercial piétonnier, ambiance village avec gare RER D",
  },
  "montgeron": {
    slug: "montgeron",
    quartiers: ["Centre-ville", "La Foret", "Le Reveil Matin", "Bois-de-Malabry"],
    rues: ["Avenue de la Republique", "Rue d'Yerres", "Rue Emile-Zola", "Boulevard du Chateau", "Avenue Jean-Jaures"],
    landmarks: ["Mairie de Montgeron", "Gare RER D Montgeron-Crosne", "Foret de Senart", "Parc de Montgeron"],
    commerces: ["Commerces Avenue de la Republique", "Centre commercial Montgeron-Nord", "Marche de Montgeron"],
    profile: "urbain",
    description: "Commune residentielle et commerciale proche de la foret de Senart, gare RER D, nombreux commerces locaux",
  },
  "epinay-sous-senart": {
    slug: "epinay-sous-senart",
    quartiers: ["Centre-ville", "Plateau", "Les Cinq-Arpents", "La Garenne"],
    rues: ["Rue Sainte-Catherine", "Avenue du General-de-Gaulle", "Rue Pierre-Brossolette", "Boulevard Charpentier", "Rue Gustave-Courbet"],
    landmarks: ["Mairie d'Epinay-sous-Senart", "Centre commercial du Plateau", "Foret de Senart"],
    commerces: ["Centre commercial des Cinq-Arpents", "Commerces de proximite", "Zone commerciale du Plateau"],
    profile: "urbain",
    description: "Commune urbaine de l'Essonne proche de la foret de Senart, tissu commercial dense et grandes ensembles",
  },
  // Default for corbeil-essonnes itself (main city)
  "corbeil-essonnes": {
    slug: "corbeil-essonnes",
    quartiers: ["Centre-ville", "Montconseil", "Rive Droite", "Tarterets", "Ermitage", "Nacelle", "Robinson"],
    rues: ["Rue de Gournay", "Rue Feray", "Avenue du President Carnot", "Rue Saint-Spire", "Quai de l'Apport-Paris"],
    landmarks: ["Cathedrale Saint-Spire", "Moulins de la Villette", "Halle du Marche", "Bords de Seine", "Theatre de Corbeil"],
    commerces: ["Centre commercial Rive Droite", "Marche de Corbeil", "Rue Feray"],
    profile: "urbain",
    description: "Prefecture historique de l'Essonne au coeur industriel et commercial, bord de Seine",
  },
};

export function getZoneLocal(slug: string): ZoneLocal | null {
  return zonesLocal[slug] || null;
}
